serverconfig:
  bindaddr: 0.0.0.0
  listenport: 8088
host:
  web1:
    ip: 192.168.3.199
    user: root
    port: 22
    password: "root"
  web2:
    ip: 192.168.1.1
    user: root
    port: 22
    password: "s df ad"
logfile:
  www_nginx:
    - path: /var/log/nginx/access.log
      host: web1
    - path: /varlog/nginx/error.log
      host: web2
  api:
    - path: /data/logs/api/api.log
    - host: web2